name: iamsimon
favicon: null
layout_spectrum: 0.76956
typography_spectrum: 0.7498421985656023
title: 'WEST END CAMERA CLUB '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#31341f'
    - '#eff3f2'
    - '#7f5d41'
    - '#c3bfbb'
  brandStrength: 0.5086586026009172
  lightness: 0.8839919390156865
  saturation: 0.657612671609968
  rhythmicContrast: 0.7998390009161085
purpose: []
